name: BugReport
description: Melde einen Fehler.
title: "[BUG]: "
labels:
  - "bug"
assignees:
  - Gamezoner

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Fehlerbeschreibung
      description: "Beschreibe hier was passiert ist, und was du gemacht hast, als es passiert ist"
      placeholder: "EnterTheProblemHere"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Fehlerreproduktion
      description: "Beschreibe hier, wenn möglich, wie man den Fehler reproduzieren kann"
      placeholder: "EnterHowToReproduceTheBugHere"
    validations:
      required: false
  - type: textarea
    id: expectation
    attributes:
      label: Erwartung
      description: "Beschreibe hier, was du erwartet hast bzw. was passieren sollte"
      placeholder: "EnterWhatYouExpectedToHappenIfYouWantTo"
    validations:
      required: false